export const albums = [
    {
        id: 1,
        artist: "Shakira",
        title: "Oral Fixation 2",
        genre: "Pop",
        year: "12-05-2006",
        img: "/albums/shakira.jpg",
        price: 100,
    },
    {
        id: 2,
        artist: "Red Hot Chili Peppers",
        title: "Stadium Arcadium",
        genre: "Rock",
        year: "13-06-2006",
        img: "/albums/StadiumArcadium.jpg",
        price: 150,
    },
    {
        id: 3,
        artist: "Gnarls Barkley",
        title: "St. Elsewhere",
        genre: "Pop",
        year: "14-04-2006",
        img: "/albums/Gnarls_Barkley.jpg",
        price: 100,
    },
    {
        id: 4,
        artist: "Skousen Niels",
        title: "Daddy Longleg",
        genre: "Dansk",
        year: "15-05-2006",
        img: "/albums/SkousenDaddyLongleg.jpg",
        price: 50,
    },
    {
        id: 5,
        artist: "Knopfler & Harris",
        title: "All The Roadrunning",
        genre: "Pop",
        year: "16-04-2006",
        img: "/albums/KnopflerHarrisRoadrunning.jpg",
        price: 100,
    },
    {
        id: 6,
        artist: "Bruce Springsteen",
        title: "We Shall Overcome The Seeger Sessions",
        genre: "Folk",
        year: "17-06-2006",
        img: "/albums/SpringsteenOvercome.jpg",
        price: 100,
    },
    {
        id: 7,
        artist: "Johnson",
        title: "Det Passer",
        genre: "Hiphop",
        year: "18-05-2006",
        img: "/albums/JohnsonPasser.jpg",
        price: 100,
    },
    {
        id: 8,
        artist: "Diverse Artister",
        title: "Eurovision Song Contest 2006",
        genre: "Pop",
        year: "19-03-2006",
        img: "/albums/Eurovision.jpg",
        price: 50,
    },
    {
        id: 9,
        artist: "Danser Med Drenge",
        title: "Vores Bedste",
        genre: "Pop",
        year: "20-04-2006",
        img: "/albums/DanserMedBedste.jpg",
        price: 100,
    },
    {
        id: 10,
        artist: "Koppel Thomas",
        title: "Improvisationer For Klaver",
        genre: "Jazz",
        year: "19-06-2006",
        img: "/albums/KoppelImprovisationer.jpg",
        price: 100,
    },
    {
        id: 11,
        artist: "Roy Orbison",
        title: "The Very Best Of",
        genre: "Pop",
        year: "22-05-2006",
        img: "/albums/OrbisonBestOf.jpg",
        price: 100,
    },
    {
        id: 12,
        artist: "Juanes",
        title: "Mi Sangre",
        genre: "Latin",
        year: "23-04-2006",
        img: "/albums/JuanesMiSangre.jpg",
        price: 100,
    },
    {
        id: 13,
        artist: "Rasmus Nøhr",
        title: "Lykkelig Smutning",
        genre: "Dansk",
        year: "24-05-2006",
        img: "/albums/RasmusNohrSmutning.jpg",
        price: 100,
    },
    {
        id: 14,
        artist: "Sidsel",
        title: "Where Are My Shoes",
        genre: "Pop",
        year: "25-05-2006",
        img: "/albums/SidselWhereShoes.jpg",
        price: 100,
    },
    {
        id: 15,
        artist: "Crazy Frog",
        title: "More Crazy hits",
        genre: "Pop",
        year: "26-05-2006",
        img: "/albums/CrazyFrogMore.jpg",
        price: 100,
    },
    {
        id: 16,
        artist: "Madonna",
        title: "Confessions On A Dancefloor",
        genre: "Pop",
        year: "27-05-2006",
        img: "/albums/MadonnaConfessions.jpg",
        price: 100,
    },
    {
        id: 17,
        artist: "Bryan Rice",
        title: "Confessional",
        genre: "Dansk",
        year: "28-05-2006",
        img: "/albums/BryanRice.jpg",
        price: 100,
    },
    {
        id: 18,
        artist: "Michael Buble",
        title: "It's time",
        genre: "Pop",
        year: "29-05-2006",
        img: "/albums/Buble.jpg",
        price: 100,
    },
    {
        id: 19,
        artist: "TV2",
        title: "De Første Kærester På Månen",
        genre: "Dansk",
        year: "30-05-2006",
        img: "/albums/TV2.jpg",
        price: 100,
    },
    {
        id: 20,
        artist: "Kelly Clarkson",
        title: "Breakaway",
        genre: "Pop",
        year: "20-05-2006",
        img: "/albums/Clarkson.jpg",
        price: 100,
    }
]